#!/bin/sh
# postrm script for grub-loopback-iso

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
      if test -e /boot/grub/grub.cfg && which update-grub >/dev/null 2>&1; then
        echo "Updating grub.cfg to make sure there are no non-existing entries being left."
        update-grub
      fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
