#!/bin/sh
# postinst script for grml-rescueboot

set -e

case "$1" in
    configure)
      # default, unless configured otherwise:
      ISO_LOCATION=/boot/grml

      if [ -r /etc/default/grml-rescueboot ] ; then
	. /etc/default/grml-rescueboot
      fi

      if ! ls "${ISO_LOCATION}"/*iso >/dev/null 2>&1 ; then
	echo "INFO: No *.iso files found inside ${ISO_LOCATION}."
        echo "INFO: Please create ${ISO_LOCATION} and place rescue ISO(s) there."
	echo "INFO: Finally invoke update-grub and enjoy your rescue system."
      else
	if ! which update-grub >/dev/null 2>&1; then
	  echo "WARN: ISOs found inside ${ISO_LOCATION} but update-grub not present (huh?)"
	else
	  echo "INFO: ISOs found inside ${ISO_LOCATION}, invoking update-grub:"
          update-grub
        fi
      fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
