#!/bin/sh
# postrm script for grml-rescueboot

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
      echo "Updating grub.cfg to make sure there are no non-existing entries being left."
      update-grub
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
